### ISSUE TITLE
FR: please co-publish on Open VSX Registry

### ISSUE THREAD

**Issue by GitMensch** [maelvls/vscode_autotools#10]
The [Open VSX Registry](https://open-vsx.org/?search=autoconf) does only include the built-in Make extension also used for VSCode, this very useful extension is currently not available.

Details on the publishing can be found at https://github.com/eclipse/openvsx/wiki/Publishing-Extensions.

**Comment by maelvls** [comment]
Excellent point; I didn’t know about openvsx and it looks like a good opportunity to “stay out” from Microsoft’s locked extension store

**Comment by GitMensch** [comment]
Friendly ping - is this something you plan to do in the near future?

**Comment by maelvls** [comment]
Hi! I finally have some time off today! I think I'll be able to do that now 🙂

I'll also document all the things that I do using `vsce` and `ovsx` so that anyone is aware of what I do behind the curtains 😅

**Comment by maelvls** [comment]
Done 👍

**Comment by GitMensch** [comment]
Worked like a charm: https://open-vsx.org/extension/maelvalais/autoconf
Thank you very much!

_Hint: the side above mentions that you may want to "claim ownership" of maelvalais._

Do you want to keep this issue open for the documentation part?

**Comment by maelvls** [comment]
Done! I added all the details of what I did in the readme

Some day I wish I had a bit of time and make sure CI does it automatically (when a tag gets pushed, CI publishes to vsce & ovsx)

> Hint: the side above mentions that you may want to "claim ownership" of maelvalais.

I'll fix that and claim ownership (by opening a PR on the open-vsx repo I think)

**Comment by GitMensch** [comment]
> Some day I wish I had a bit of time and make sure CI does it automatically (when a tag gets pushed, CI publishes to vsce & ovsx)

Sounds like something to be tracked as new issue :-)
[And it seems this repo does not use any kind of CI, does it? You may leave your preferences [super easy, hard-wired to GitHub (like the GitHub Actions) / not hardwired, ...] in that issue, just in case someone looks at it some day ;-)]

**Comment by GitMensch** [comment]
@maelvls just to recheck - is ther any CI yet? Do you want to create an issue about this part?

**Comment by maelvls** [comment]
You are right, let's create a story about that 👍 
Here is the story: https://github.com/maelvls/vscode_autotools/issues/13
