### ISSUE TITLE
possible split of README.md

### ISSUE THREAD

**Issue by GitMensch** [maelvls/vscode_autotools#12]
I suggest (and would also do this if you like the idea but not want to do it on your own) to split the readme file.

Most important:
-> CHANGELOG.md (also leads commonly to a recognized changelog)
-> HACKING / DEVNOTES / DEVELOP / whatever -> including the way to build and publish
-> possibly add some text how great this extension is

**Comment by maelvls** [comment]
I moved the "dev" related things to `DEVELOPMENT.md`.

Regarding `CHANGELOG.md`, I agree, I should use that file instead of shoving everything into the readme.
