### ISSUE TITLE
Contribute fixes back to sublime_autotools

### ISSUE THREAD

**Issue by ptomato** [maelvls/vscode_autotools#5]
Hi! Nice work, how interesting to see that sublime_autotools was useful for VSCode as well!

Would you be interested in porting some of your fixes back to sublime_autotools? If you made some pull requests I would be happy to merge them.

**Comment by jannick0** [comment]
@maelvalais ptomato/sublime_autotools#6 would be an issue I encountered when using vscode_autotools, but addressed in sublime_autotools and - hopefully - solved in the suggested PR ptomato/sublime_autotools#6. So this would be rather something to merge into your repo?

Merci.

**Comment by maelvalais** [comment]
Hi!! 👋 
Thank you both for reaching out!! Always heartwarming to see that people want to contribute back 😊 I’ll be more than happy to accept PRs!

As @jannick0 mentioned, we could first merge everything from sublime_autotools. I’ll try to do that later today.

**Comment by maelvalais** [comment]
Hi!
I updated my build scripts so that I can modify the `JSON-tmLanguage` and generate YAML and tmLanguage files from it. This was necessary in order to merge from upstream (ptomato/sublime_autotools) as ptomato uses json as its source of truth.

**Comment by maelvalais** [comment]
There we go, I just merged your change (see https://github.com/maelvalais/vscode_autotools/commit/3e2062d9300ab7f3ce7665195aec34f274b7cad8). It is now live on vscode, the extension should update itself to 0.0.9.

**Comment by jannick0** [comment]
Great - many thanks!

**Comment by ptomato** [comment]
I would be happy to switch to YAML upstream. When I first created the repo, Sublime Text didn't support that yet.

**Comment by ptomato** [comment]
I have made https://github.com/ptomato/sublime_autotools/pull/8 which switches sublime_autotools to YAML and I think pulls in all the highlighting bug fixes from vscode_autotools. Let me know what you think of it.

I didn't import the "rule2" and "recipe" changes to Makefile2 yet, they don't seem to work correctly in Sublime.

**Comment by GitMensch** [comment]
@ptomato Where does this issue stand (other than the PR in your repo seeming to be stale)?

**Comment by maelvls** [comment]
I wish we could find a way to have the same YAML source between sublime and vscode 😅

**Comment by ptomato** [comment]
> @ptomato Where does this issue stand (other than the PR in your repo seeming to be stale)?

OK, patience please! I'm happy to rebase it, but as I mentioned in my previous comment I'd like some feedback on whether it is going to fit the purpose of allowing these two projects to share code.

**Comment by ptomato** [comment]
sublime_autotools now has YAML sources and I think I've pulled in all the improvements that vscode_autotools has made.

**Comment by ptomato** [comment]
I think this can be closed now, there's nothing else to do here?
