### ISSUE TITLE
autoconf: complete PKG macro family

### ISSUE THREAD

**Issue by jannick0** [maelvls/vscode_autotools#6]
Hi again,

would it be possible to merge PR ptomato/sublime_autotools#9 ptomato approved for sublime_autotools?  Please let me know if you want me to open a separate PR for this here in your repo.   

Many thanks!

**Comment by maelvls** [comment]
Sure. Sorry for the delay, I got caught up in my new job. I'll do that right now.

**Comment by maelvls** [comment]
**Update:** wow, so many conflicts, that's going to take some time
I don't even know how to proceed at this point :(

**Comment by jannick0** [comment]
Then I could draft a PR for your repo with the edits in ptomato#9 you could simply pull without any conflicts I hope.  I'll do that right now.

**Comment by maelvls** [comment]
I pushed a new release with these changes (maelvalais.autoconf@0.1.0)
