### ISSUE TITLE
Request for new maintainers

### ISSUE THREAD

**Issue by maelvls** [maelvls/vscode_autotools#9]
Just in case I disappear or anything else, would anyone be interested in becoming a maintainer of this project?

- I would add you as an “Admin” of the project.
- I'm totally fine with anything happening to this project! 🙂

**Comment by GitMensch** [comment]
As this is a really useful extension to me I'd say "yes", but I don't anything about sublime only something about vscode and [theia](https://theia-ide.org/) and not really much about the different extension options both offer. I think I *could* handle PR (after a very rough testing) and am open to learn new stuff, but I'm possibly not the one you're looking for anything other than the issue of you hopefully not "disappearing or anything else".

**Comment by maelvls** [comment]
Thanks for taking the time to answer 🙂 I don’t really know anything about Sublime either to be honest 😇 

I’m pretty sure I won’t disappear though lol. I’m not using this extension anymore and I wish someone else would take over

But I’ll maintain it in the meantime 👍

**Comment by GitMensch** [comment]
It's a bit sad that you don't use that any more - but I want to thank you that you still maintain it.
I've just seen you invitation to join the repo, which - of course - expired. I'm not sure if I'm the right one to maintain this extension (I'm quite "full" already with my main free software project and I've still "just started" to hack vscode extensions), but I do use this extension quite regularly.

In general: could you check https://github.com/maelvls/vscode_autotools/compare/master...ptomato:master and have a look for integrating "missing" pieces?

... in the meantime I'll work on adding a problem matcher to this extension for autoconf generated testsuites (that's json only, I should be able to do that).

**Comment by maelvls** [comment]
Hey,

I spent some time updating this fork. It is now up to date with ptomato/sublime_autotools.
